# Descomposición en valores singulares (SVD)

## Definición

La SVD generaliza la EVD a matrices rectangulares, del tipo $\mathbf{A}\in\mathbf{R}^{m\times n}$:
$$\mathbf{A}=\mathbf{U}\mathbf{S}\mathbf{V}^t%
=\sigma_1\boldsymbol{u}_1\boldsymbol{v}_1^t+\cdots+\sigma_r\boldsymbol{u}_r\boldsymbol{v}_r^t$$
* $\mathbf{U}\in\mathbf{R}^{m\times m}$ es una matriz de columnas ortonormales ($\mathbf{U}^t\mathbf{U}=\mathbf{I}$) que llamamos **vectores singulares izquierdos**
* $\mathbf{S}\in\mathbf{R}^{m\times n}$ incluye $r=\min(m, n)$ **valores singulares** $\sigma_i\geq 0$ en su diagonal; ceros en el resto
* $\mathbf{V}\in\mathbf{R}^{n\times n}$ es una matriz de filas y columnas ortonormales ($\mathbf{V}^t\mathbf{V}=\mathbf{V}\mathbf{V}^t=\mathbf{I}$); sus columnas son los **vectores singulares derechos**

## Conexión entre la SVD y la EVD

Si $\mathbf{A}$ es una matriz cuadrada, real, simétrica y definida positiva, se cumple que:
* Los valores singulares son los valores propios
* Los vectores singulares izquierdos y derechos son los vectores propios (salvo cambios de signo):
$$\;\mathbf{A}=\mathbf{U}\mathbf{S}\mathbf{V}^t=\mathbf{U}\mathbf{S}\mathbf{U}^t=\mathbf{U}\mathbf{S}\mathbf{U}^{-1}$$

In [4]:
import numpy as np

A = np.array([ [5/2, 3/2], [3/2, 5/2] ])
L, E = np.linalg.eigh(A) # L (y E) en orden no descendente
L, E = L[::-1], E[::-1] # L (y E) en orden no ascendente
print("EVD:\n", L, "\n", E, "\n")
U, S, Vt = np.linalg.svd(A)
print("SVD:\n", U, "\n", S, "\n", Vt)

EVD:
 [4. 1.] 
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]] 

SVD:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] 
 [4. 1.] 
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


## SVD truncada

Sea $\mathbf{A}=\mathbf{U}\mathbf{S}\mathbf{V}^t$ la SVD de una matriz $\mathbf{A}\in\mathbf{R}^{m\times n}$. Sea
$\mathbf{\hat{A}}_K=\mathbf{U}_K\mathbf{S}_K\mathbf{V}_K^t$ una aproximación de $\mathbf{A}$ de rango $K$ construida a partir de sus $K$ mayores valores singulares, junto con sus $K$ vectores singulares asociados, izquierdos y derechos.
Se puede comprobar que $\mathbf{\hat{A}}_K$ es la mejor aproximación de $\mathbf{A}$ en norma Frobenius (al cuadrado),
$\lVert\mathbf{A}-\hat{\mathbf{A}}_K\rVert_F^2$.

