# Descomposición en valores singulares (SVD)

## Definición

La SVD generaliza la EVD a matrices rectangulares, del tipo $\mathbf{A}\in\mathbf{R}^{m\times n}$:
$$\mathbf{A}=\mathbf{U}\mathbf{S}\mathbf{V}^t%
=\sigma_1\boldsymbol{u}_1\boldsymbol{v}_1^t+\cdots+\sigma_r\boldsymbol{u}_r\boldsymbol{v}_r^t$$
* $\mathbf{U}\in\mathbf{R}^{m\times m}$ es una matriz de columnas ortonormales ($\mathbf{U}^t\mathbf{U}=\mathbf{I}$) que llamamos **vectores singulares izquierdos**
* $\mathbf{S}\in\mathbf{R}^{m\times n}$ incluye $r=\min(m, n)$ **valores singulares** $\sigma_i\geq 0$ en su diagonal; ceros en el resto
* $\mathbf{V}\in\mathbf{R}^{n\times n}$ es una matriz de filas y columnas ortonormales ($\mathbf{V}^t\mathbf{V}=\mathbf{V}\mathbf{V}^t=\mathbf{I}$); sus columnas son los **vectores singulares derechos**

## Conexión entre la SVD y la EVD

Si $\mathbf{A}$ es una matriz cuadrada, real, simétrica y definida positiva, se cumple que:
* Los valores singulares son los valores propios
* Los vectores singulares izquierdos y derechos son los vectores propios (salvo cambios de signo):
$$\;\mathbf{A}=\mathbf{U}\mathbf{S}\mathbf{V}^t=\mathbf{U}\mathbf{S}\mathbf{U}^t=\mathbf{U}\mathbf{S}\mathbf{U}^{-1}$$

In [1]:
import numpy as np

A = np.array([ [5/2, 3/2], [3/2, 5/2] ])
L, E = np.linalg.eigh(A)
print("EVD:\n", L, "\n", E, "\n")
U, S, Vt = np.linalg.svd(A)
print("SVD:\n", U, "\n", S, "\n", Vt)

EVD:
 [1. 4.] 
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]] 

SVD:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] 
 [4. 1.] 
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
